### PR TITLE
fix cache store bug

### PR DESCRIPTION
**Pull request by JoneXie1986**
"this" is of the wrong scope.Fix the bug with defining a new varible "self".

### CODE REVIEW

**Comment by jackycute** [comment]
Please merge this, quiet important PR.

**Comment by doublerebel** [comment]
:+1: LGTM

**Comment by indutny** [comment]
Gosh, I really feel terrible about this. Sorry, guys, I forgot to "watch" the repo after creating it.

I'm going to land it, because the error is obvious, but may I ask you if you might be interested in contributing a test case for this?

Thank you!

**Comment by indutny** [comment]
Landed in a3e89df

**Pull request closed without merging**
